repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.4  # Use the latest stable version if needed
    hooks:
      - id: sqlfluff-fix
        args: [--dialect, postgres]  # change dialect to your actual one (e.g., postgres, bigquery, etc.)
        files: \.sql$