repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.4
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, postgres]
        files: \.sql$
        exclude: ""
  - repo: local
    hooks:
      - id: sqlfluff-fix-and-add
        name: SQLFluff Fix + Git Add
        entry: bash scripts/sqlfluff_fix_and_add.sh
        language: system
        files: \.sql$
        pass_filenames: true
